### ISSUE TITLE
parameters: add option "hidden" to parameters to not show values in gui

### ISSUE THREAD

**Issue by fgoebel** [theforeman/foreman-ansible-modules#1024]
- [x] global_parameter
- [ ] smart_class_parameter
- [ ] nested parameter (org, loc)
- [ ] domain, subnet, host, hostgroup, ... ("direct" params, for the lack of a better name)

##### SUMMARY
When I set parameters with these modules (global_parameters, organizations, locations,...) it is not possible to toggle the "hidden" option like in the gui.

```
# task example:
- theforeman.foreman.location:
    username: "{{ foreman_web_user }}"
    password: "{{ foreman_web_password }}"
    server_url: "{{ foreman_server }}"
    name: "some location"
    organizations:
    - "some Org"
    state: present
    parameters:
      - name: password
        parameter_type: string
        value: verySecretPasswordIdoNotWantToShowInGui
        hidden: true
```

What do you think?

##### ISSUE TYPE
 - Feature Idea

**Comment by mdellweg** [comment]
At least for `global_parameter` this should be fairly easy to implement.
Do you want to give it a try?

**Comment by mdellweg** [comment]
Oh, i went ahead, and did some experiments. Turns out, that hidden values are also hidden from the api. So creating a hidden parameter will not be idempotent. Also `hidden_value` is reported as `hidden_value?` by the API. This needs a little bit more designing.

https://theforeman.org/api/2.1/apidoc/v2/common_parameters/show.html

**Comment by fgoebel** [comment]
hey mdellweg,
thank you for your first test and your answer to my feature request.

I have never done any development yet, so i think i can barely help with this.
But if you would maybe assist me, I am happy to test your changes and maybe get some development started this way!

**Comment by mdellweg** [comment]
I removed the "easy" label, because the thing is a bit tricky. We are in the process of pushing a breaking change through apypie to solve this. But, i invite you to test my PR #1025 .

**Comment by evgeni** [comment]
#1025 is now merged.

while reviewing it, we noticed that `smart_class_parameter` has partial support for hidden parameters already, but is missing the idempotency bit that @mdellweg implemented for `global_parameter` in #1025 

and this still needs porting to the other parameter handlers we have (yay)

**Comment by ExplGamma** [comment]
Linking for posterity: https://github.com/theforeman/foreman-ansible-modules/pull/1785 added support for creating hidden params. Unfortunately I've been unable to get them working with hostgroups when updating params (ie just trying to set previously non-hidden params as hidden)
