### ISSUE TITLE
Port available modules to apypie

### ISSUE THREAD

**Issue by mdellweg** [theforeman/foreman-ansible-modules#274]
- [x] foreman_architecture
- [x] foreman_auth_source_ldap
- [x] foreman_bookmark
- [x] foreman_compute_attribute
- [x] foreman_compute_profile
- [x] foreman_compute_resource
- [x] foreman_config_group
- [x] foreman_domain
- [x] foreman_environment
- [x] foreman_global_parameter
- [x] foreman_host
- [x] foreman_host_power (#450)
- [x] foreman_hostgroup
- [x] foreman_installation_medium
- [x] foreman_job_template (#440)
- [x] foreman_location
- [x] foreman_operatingsystem
- [x] foreman_organization
- [x] foreman_os_default_template
- [x] foreman_provisioning_template
- [x] foreman_ptable
- [x] foreman_realm
- [x] foreman_role
- [x] foreman_search_facts
- [x] foreman_setting
- [x] foreman_snapshot
- [x] foreman_subnet
- [x] foreman_user
- [x] katello_activation_key
- [x] katello_content_credential
- [x] katello_content_view (https://github.com/theforeman/foreman-ansible-modules/pull/405)
- [ ] katello_content_view_filter (#471)
- [x] katello_content_view_version (#445)
- [x] katello_host_collection
- [x] katello_lifecycle_environment
- [x] katello_manifest
- [x] katello_product
- [x] katello_repository
- [x] katello_repository_set
- [x] katello_sync (https://github.com/theforeman/foreman-ansible-modules/pull/424)
- [x] katello_sync_plan
- [x] katello_upload
- [x] ~~redhat_manifest~~ (not `nailgun` based)

**Comment by evgeni** [comment]
I'd like to raise the question what should happen with modules that don't have tests and are thus not ported to the new API we introduced in February.

Given they are preserved them in the `nailgun` branch and I think they are kind of a blocker for the 0.1.0 milestone.

Some of them are deprecated anyways, so I'd argue we should just remove them.
For those that don't have  a replacement, we should prioritize writing tests, but I'd add a hard deadline (October?) by which all modules that are not tested are moved to `/dev/null`.

**Comment by mdellweg** [comment]
I am ok with deleting them. They continue to live on the nailgun branch, and can be reintroduced at any later time. Carrying modules around that are not covered by tests is probably not worth the efford.

**Comment by mdellweg** [comment]
And only 4 to close the foreman-ping issue.

**Comment by evgeni** [comment]
Yes!

**Comment by mdellweg** [comment]
Two of those ready for review.

**Comment by evgeni** [comment]
2 modules to go, one with an open PR. :fireworks:
