### ISSUE TITLE
comply with the Ansible Collections Checklist

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-ansible-modules#910]
there is a checklist at https://github.com/ansible-collections/overview/blob/master/collection_requirements.rst which we should check and try to comply with

known todos:
- [x] run sanity against latest stable (#909)
- [x] use FQCN in all module references (docs, examples, etc) (#913)
- [x] add minimum supported Ansible version to meta/runtime.yml (but I need to talk to @gundalow how to handle 2.8 support) (#914)
- [x] add changelog (#917)
- [x] add version_added to all plugins that were not in ansible 2.9 (#922)

**Comment by evgeni** [comment]
I think we're done.

@ehelms @mdellweg would one of you please read the linked document and briefly verify we're compliant?

**Comment by mdellweg** [comment]
I don't understand and also don't see anything for:
- [ ] galaxy.yml : "dependencies MUST be set to '>=1.0.0'"
- [ ] DOCUMENTATION : "Use collection version numbers for version_added (otherwise version_added_collection must be provided, but this is discouraged)"

Everything else is fine. And wrt the unittest section we are miles ahead of that document.

**Comment by evgeni** [comment]
1. Collections can depend on other collections, and I read that requirement as "you're only allowed to depend on stable (not 0.x) versions. We don't have any dependencies, so "done".
2. Hmm, I guess we could add a "version_added: 1.1.0" to the http_proxy module, as that's new in the next release?

**Comment by mdellweg** [comment]
See, i read that different:
https://github.com/ansible-collections/overview/issues/106

**Comment by felixfontein** [comment]
New modules and plugins should have version_added. Otherwise neither the changelog generator nor users know when the module/plugin was added.

**Comment by mdellweg** [comment]
The question is whether _all_ modules / plugins _need_ to specify something, or only the ones added after 1.0.0.

**Comment by felixfontein** [comment]
There's no need to add `version_added` for anything that already was in Ansible 2.9. Some collections also add version_added for these, but others don't (my personal opinion is not to). In general, `version_added` is optional, but it is good practice to use it correctly - it makes the documentation a lot more useful, and your users will thank you.

**Comment by mdellweg** [comment]
Almost nothing here has been in ansible 2.9. So i guess, adding a version_added: 1.0.0 to everything (but http_proxy which gets 1.1.0) is in order?

**Comment by felixfontein** [comment]
Sounds good to me.

**Comment by evgeni** [comment]
👍

**Comment by evgeni** [comment]
I'd call this done, unless anyone disagrees?
